services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod
    ports:
      - "${DB_PORT:-5432}:5432"
    profiles:
      - prod

  web:
    build: .
    entrypoint: /entrypoint.sh
    volumes:
      - .:/app
    env_file:
      - .env.${DJANGO_ENV:-local}
    ports:
      - "8000:8000"

volumes:
  postgres_data:
